---
# tasks file for ansible-role-pgcenter

- import_tasks: pgcenter.yml
  ignore_errors: yes
  tags: pgcenter

- import_tasks: bash_alias.yml
  when: set_pgcenter_alias != "false"
  ignore_errors: yes
  tags: pgcenter_alias
